[build]
build-std = false                              # do not build the std library. has precedence over xargo
xargo = false                                   # enable the use of xargo by default
zig = false                                    # do not use zig cc for the builds
default-target = "x86_64-unknown-linux-gnu"    # use this target if none is explicitly provided
pre-build = [ "apt-get update && apt-get --assume-yes install libcairo2-dev libatk1.0-dev  libpango1.0-dev libgtk-3-dev  glib-2.0-dev libglib2.0-dev" ]

[target.x86_64-unknown-linux-gnu]
pre-build = [ "apt-get update && apt-get --assume-yes install libpango1.0 gir1.2-pango-1.0" ]

# image = "rust:slim"

# [target.x86_64-pc-windows-gnu]
# image = "rust:latest"
#  apt install -y g++-mingw-w64-x86-64 

[target.arm-unknown-linux-gnueabi]
pre-build = [ "apt-get update && apt-get --assume-yes install libpango1.0 gir1.2-pango-1.0" ]


[target.aarch64-unknown-linux-gnu]
pre-build = [ "dpkg --add-architecture aarch64 && apt-get update && apt-get --assume-yes install libpango1.0:aarch64 gir1.2-pango-1.0:aarch64" ]

