import { LineEdit, Button, ComboBox, GridBox , CheckBox, TextEdit} from "std-widgets.slint";

export component AnyServeUI inherits Window {
    callback start_ftp_server();
    callback stop_ftp_server();

    in-out property <string> le_path <=> lePath.text;
    in-out property <string> le_bind_address <=> leBindAddress.text;
    in-out property <string> te_logs <=> teLogs.text;

    private property <bool> any-checked;
    private property <length> labels-width: 35pt;

    title: "Anyserve";
    height: 500px;
    GridBox {
        gb1 := GridBox {
            row: 0;
            Text {
                col: 0;
                width: labels-width;
                text: "Path";
                horizontal-alignment: right;
                vertical-alignment: center;
            }
            lePath := LineEdit {
                col: 1;
                text: "~/Public/";
            }
            btPath := Button {
                col: 2;
                text: "Select";
            }
        }
        gb2 := GridBox {
            row: 1;
            Text {
                col: 0;
                width: labels-width;
                text: "Bind\naddress";
                horizontal-alignment: right;
                vertical-alignment: center;
            }
            leBindAddress := LineEdit {
                col: 1;
                text: "127.0.0.1:2121";
            }
        }
        gb3 := GridBox {
            row: 2;
            cbFTP := CheckBox {
                col: 0;
                text: "FTP";
            }
            cbTFTP := CheckBox {
                col: 1;
                text: "TFTP";
                enabled: false;
            }
            cbHTTP := CheckBox {
                col: 2;
                text: "HTTP";
                enabled: false;
            }
            cbDHCP := CheckBox {
                col: 3;
                text: "DHCP";
                enabled: false;
            }
        }
        btStart := Button {
            row: 3;
            text: "Start";
            checkable: true;

            clicked => {
                if (btStart.checked) {
                    any-checked = false;

                    if (cbFTP.checked){
                        teLogs.text += "Startin FTP server\n";
                        any-checked = true;
                        root.start_ftp_server()
                    }

                    if (cbHTTP.checked){
                        teLogs.text += "Startin HTTP server\n";
                        any-checked = true;
                    }

                    if (cbTFTP.checked){
                        teLogs.text += "Startin TFTP server\n";
                        any-checked = true;
                    }

                    if (cbDHCP.checked){
                        teLogs.text += "Startin DHCP server\n";
                        any-checked = true;
                    }

                    if (any-checked) {
                        btStart.text = "Stop";
                    }
                    else {
                        teLogs.text += "Nothing to start...\n";
                        btStart.checked = false;
                    }
                }
                else {
                    btStart.text = "Start";
                    teLogs.text += "Stopped\n";
                    root.stop_ftp_server();
                }

                cbFTP.enabled = !btStart.checked;
                lePath.enabled = !btStart.checked;

                // gb1.enabled = !btStart.checked;
            }
        }
        teLogs := TextEdit {
            row: 4;
            read-only: true;
         }
    }
}
