import { LineEdit, Button, ComboBox, GridBox , CheckBox, TextEdit, ScrollView, StandardListView } from "std-widgets.slint";

export component AnyServeUI inherits Window {
    callback start_ftp_server();
    callback stop_ftp_server();

    in-out property <string> le_path <=> lePath.text;
    in-out property <string> le_bind_address <=> leBindAddress.text;

    in-out property <string> te_logs <=> teLogs.text;

    in-out property <length> te_vh <=> teLogs.viewport-height;
    in-out property <length> te_h <=> teLogs.height;
    in-out property <length> te_vy <=> teLogs.viewport-y;

    private property <bool> any-checked;
    private property <length> labels-width: 35pt;

    title: "Anyserve";
    preferred-height: 680px;
    preferred-width: 500px;
    GridBox {
        gb1 := GridBox {
            row: 0;
            Text {
                col: 0;
                width: labels-width;
                text: "Path";
                horizontal-alignment: right;
                vertical-alignment: center;
            }
            lePath := LineEdit {
                col: 1;
                text: "/tmp/";
            }
            btPath := Button {
                col: 2;
                text: "Select";
            }
        }
        gb2 := GridBox {
            row: 1;
            Text {
                col: 0;
                width: labels-width;
                text: "Bind\naddress";
                horizontal-alignment: right;
                vertical-alignment: center;
            }
            leBindAddress := LineEdit {
                col: 1;
                text: "127.0.0.1:2121";
            }
        }
        gb3 := GridBox {
            row: 2;
            cbFTP := CheckBox {
                col: 0;
                text: "FTP";
            }
            cbTFTP := CheckBox {
                col: 1;
                text: "TFTP";
                enabled: false;
            }
            cbHTTP := CheckBox {
                col: 2;
                text: "HTTP";
                enabled: false;
            }
            cbDHCP := CheckBox {
                col: 3;
                text: "DHCP";
                enabled: false;
            }
            //Spacer
            Rectangle {}
        }
        btStart := Button {
            row: 3;
            text: "Start";
            checkable: true;

            clicked => {
                if (btStart.checked) {
                    any-checked = false;

                    if (cbFTP.checked){
                        any-checked = true;
                        root.start_ftp_server()
                    }

                    if (cbHTTP.checked){
                        any-checked = true;
                    }

                    if (cbTFTP.checked){
                        any-checked = true;
                    }

                    if (cbDHCP.checked){
                        any-checked = true;
                    }

                    if (any-checked) {
                        btStart.text = "Stop";
                    }
                    else {
                        btStart.checked = false;
                    }
                }
                else {
                    btStart.text = "Start";
                    root.stop_ftp_server();
                }

                // cbFTP.enabled = !btStart.checked;
                // lePath.enabled = !btStart.checked;
                // gb1.enabled = !btStart.checked;
            }
        }
        teLogs := TextEdit {
            row: 4;
            read-only: true;
            wrap: no-wrap;
        }
    }
}
