import { LineEdit, Button, ComboBox, GridBox , CheckBox, TextEdit, ScrollView, StandardListView , HorizontalBox} from "std-widgets.slint";

export component AnyServeUI inherits Window {
    callback startstop_ftp_server(bool);
    callback show-open-dialog;


    in-out property <string> le_path <=> lePath.text;
    in-out property <string> le_bind_address <=> leBindAddress.text;

    in-out property <string> te_logs <=> teLogs.text;

    private property <length> labels-width: 35pt;

    public function is_connected (connected: bool) {
        lePath.enabled = !connected;
        btPath.enabled = !connected;
        leBindAddress.enabled = !connected;
        btStartFTP.checked = connected;
    }

    private property <length> pos;
    private property <length> new_pos;

    public function is_glued() -> bool {
        pos = (teLogs.viewport-height + 38.0px - teLogs.height) * -1.0;
        if (teLogs.viewport_y == pos) {
            return true;
        }
        return false;
    }

    public function textedit_scroll_to_end () {
        // TODO: make sure this "frame-margin" = 38 is true for all the OSs. Maybe calculate it in the begining
        new_pos = (teLogs.viewport-height + 38.0px - teLogs.height) * -1.0;
        teLogs.viewport_y = new_pos;
    }

    title: "Anyserve";
    preferred-height: 680px;
    preferred-width: 500px;
    GridBox {
        GridBox {
            row: 0;
            Text {
                col: 0;
                width: labels-width;
                text: "Path";
                font-weight: 10;
                horizontal-alignment: right;
                vertical-alignment: center;
            }
            lePath := LineEdit {
                col: 1;
                text: "/tmp/";
            }
            btPath := Button {
                col: 2;
                text: "📂";
                clicked => { root.show-open-dialog(); }
            }
        }
        GridBox {
            row: 1;
            Text {
                col: 0;
                width: labels-width;
                text: "Bind\naddress";
                horizontal-alignment: right;
                vertical-alignment: center;
            }
            leBindAddress := LineEdit {
                col: 1;
                text: "127.0.0.1:2121";
            }
        }
        GridBox {
            row: 2;

            btStartFTP := Button {
                col: 0;
                width: 120pt;
                text: "Start FTP";
                checkable: true;

                clicked => {
                    root.startstop_ftp_server(btStartFTP.checked);
                    root.is_connected(btStartFTP.checked);

                    if (btStartFTP.checked) { btStartFTP.text = "Stop FTP"; }
                    else { btStartFTP.text = "Start FTP"; }
                }
            }
            Rectangle {}
        }

        teLogs := TextEdit {
            row: 3;
            read-only: true;
            wrap: no-wrap;
        }
    }
}
