import { LineEdit, Button, ComboBox, GridBox , CheckBox, TextEdit} from "std-widgets.slint";

export component AnyServeUI inherits Window {
    callback start_ftp_server();
    private property <bool> any-checked;

    title: "Anyserve";
    height: 500px;
    GridBox {
        GridBox {
            row: 0;
            t1 := LineEdit {
                col: 0;
                text: "~/Public/";
            }
            btPath := Button {
                col: 1;
                text: "Select";
            }
        }
        // TODO: Add a listbox/combo here with the possible interfaces to use. Multiple or all poissible
        // TODO: Add the possibility to filter by IP
        gb1 := GridBox {
            row: 1;
            cbFTP := CheckBox {
                col: 0;
                text: "FTP";
            }
            cbTFTP := CheckBox {
                col: 1;
                text: "TFTP";
                enabled: false;
            }
            cbHTTP := CheckBox {
                col: 2;
                text: "HTTP";
                enabled: false;
            }
            cbDHCP := CheckBox {
                col: 3;
                text: "DHCP";
                enabled: false;
            }
        }
        btStart := Button {
            row: 2;
            text: "Start";
            checkable: true;

            clicked => {
                if (btStart.checked) {
                    any-checked = false;

                    if (cbFTP.checked){
                        te1.text += "Startin FTP server\n";
                        any-checked = true;
                        root.start_ftp_server()
                    }

                    if (cbHTTP.checked){
                        te1.text += "Startin HTTP server\n";
                        any-checked = true;
                    }

                    if (cbTFTP.checked){
                        te1.text += "Startin TFTP server\n";
                        any-checked = true;
                    }

                    if (cbDHCP.checked){
                        te1.text += "Startin DHCP server\n";
                        any-checked = true;
                    }

                    if (!any-checked) {
                        te1.text += "Nothing to start...\n";
                        btStart.checked = false;
                    }
                }
                else {
                    te1.text += "Stopped\n";
                }
                cbFTP.enabled = !btStart.checked;
                t1.enabled = !btStart.checked;
            }
        }
        te1 := TextEdit {
            row: 3;
            read-only: true;
         }
    }
}
