import { LineEdit, Button, ComboBox, GridBox , CheckBox, TextEdit} from "std-widgets.slint";

export component AnyServeUI inherits Window {
    // returns true if the string parameter is a valid date
    pure callback validate-date(string) -> bool;
    validate-date(_) => { true }
    // returns true if the first date is before the second date and they are both valid
    pure callback compare-date(string, string) -> bool;
    compare-date(a, b) => { a <= b }
    private property <bool> message-visible;
    height: 500px;
    GridBox {
        t1 := LineEdit {
            row: 0;
            text: "/path/to/dir";
        }
        gb1 := GridBox {
            row: 1;
            cbFTP := CheckBox {
                col: 0;
                text: "FTP";
                enabled: true;
            }
            CheckBox {
                col: 1;
                text: "TFTP";
                enabled: false;
            }
            CheckBox {
                col: 2;
                text: "HTTP";
                enabled: false;
            }
            CheckBox {
                col: 3;
                text: "DHCP";
                enabled: false;
            }
        }
        Button {
            row: 2;
            text: "Start";
            checkable: true;
            clicked => { te1.text += "Clicked\n"; }
        }
        te1 := TextEdit { 
            row: 3;
            read-only: true;
         }
    }
}
