name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always
  TARGETS: "x86_64-pc-windows-gnu x86_64-unknown-linux-gnu armv7-unknown-linux-gnueabihf aarch64-unknown-linux-gnu"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    ##################################
    # - name: Cache Rust dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       target

    ###################################
    - name: Setup for Linux x86_64
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build for Linux x86_64
      continue-on-error: false
      run: cargo build --release

    - name: Test for Linux x86_64
      continue-on-error: true
      run: cargo test --release
